name: Release Extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: |
          mkdir -p dist
          bun run build
          ls -la dist || echo "dist directory not found"

      - name: Copy public files
        run: |
          mkdir -p dist
          cp -r public/* dist/
          ls -la dist

      - name: Create unpacked extension ZIP
        run: |
          cd dist
          zip -r ../extension-unpacked.zip *
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            extension-unpacked.zip
          body: |
            ## Quick Installation
            1. Download `extension-unpacked.zip`
            2. Extract the ZIP file to a folder
            3. Open Chrome and go to `chrome://extensions`
            4. Enable "Developer mode" in the top right
            5. Click "Load unpacked" and select the folder you extracted
          draft: false
          prerelease: false
          generate_release_notes: true
