name: Release Extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: |
          mkdir -p dist
          bun run build
          ls -la dist || echo "dist directory not found"

      - name: Copy public files
        run: |
          mkdir -p dist
          cp -r public/* dist/
          ls -la dist

      - name: Create source ZIP (for direct loading)
        run: |
          zip -r source.zip . -x "*.git*" "node_modules/*" "dist/*"

      - name: Create build ZIP (for Chrome Web Store)
        run: zip -r extension.zip dist/*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            source.zip
            extension.zip
          body: |
            ## Installation Instructions
            1. Download `source.zip`
            2. Extract the ZIP file
            3. Install dependencies: `bun install`
            4. Build the extension: `bun run build`
            5. Open Chrome and go to `chrome://extensions`
            6. Enable "Developer mode" in the top right
            7. Click "Load unpacked" and select the `dist` directory
          draft: false
          prerelease: false
          generate_release_notes: true
